name: Compile notes and update pdf

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows for manual triggers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake texlive-full ghostscript

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..
        continue-on-error: false

      - name: Compile LaTeX documents
        run: |
          chmod +x ./scripts/compile-notes.sh
          cd build
          ../scripts/compile-notes.sh

      - name: Commit and Push PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          cp build/*.pdf .
          git add *.pdf
          git commit -m "Notes updated ${{ steps.get-date.outputs.date }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}